### PR TITLE
translated kpu.md

### PR DESCRIPTION
**Pull request by laurentopia**

### CODE REVIEW

**Comment by laurentopia** [comment]
added fft.md, pure google translation with just one correction: amplitude with an 's'

**Comment by laurentopia** [comment]
> 
> 
> Should be lowercase first letter
> 
> ```
> Import sensor
> Import image
> Import lcd
> Import KPU as kpu
> Index=3
> Lcd.init()
> Sensor.reset()
> Sensor.set_pixformat(sensor.RGB565)
> Sensor.set_framesize(sensor.QVGA)
> Sensor.run(1)
> Task=kpu.load(0x300000)
> Img=image.Image()
> Info=kpu.netinfo(task)
> Layer=info[index]
> w=layer.wo()
> h=layer.ho()
> Num=int(320*240/w/h)
> List=[None]*num
> X_step=int(320/w)
> Y_step=int(240/h)
> Img_lcd=image.Image()
> WhiImport sensor
> Import image
> Import lcd
> Import KPU as kpu
> Index=3
> Lcd.init()
> Sensor.reset()
> Sensor.set_pixformat(sensor.RGB565)
> Sensor.set_framesize(sensor.QVGA)
> Sensor.run(1)
> Task=kpu.load(0x300000)
> Img=image.Image()
> Info=kpu.netinfo(task)
> Layer=info[index]
> w=layer.wo()
> h=layer.ho()
> Num=int(320*240/w/h)
> List=[None]*num
> X_step=int(320/w)
> Y_step=int(240/h)
> Img_lcd=image.Image()
> ```

I don't know what you're refering to, so feel free to correct

**Comment by laurentopia** [comment]
oh I get it now, gtranslate is so smart it knows better, am i right?

**Comment by laurentopia** [comment]
case fixed!

**Comment by Neutree** [comment]
ok, thanks~~wait for a moment, doc will automatically update
> build progress: https://travis-ci.org/sipeed/MaixPy_DOC

**Pull request merged**
